name: youtube_music_clone
description: A YouTube Music clone application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^6.1.5
  youtube_player_flutter: ^8.1.2
  provider: ^6.0.5
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  # Yeni eklenen paketler
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.1.0
  youtube_explode_dart: ^2.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  audio_session: ^0.1.18
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/